# -*- coding: utf-8 -*-
"""SnapMind.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cVoIgynZ7zByIM4AeV-U17FW91zuM6rr
"""

import os

base = "/content/data"
# 아래 9개를 실제 클래스 이름으로 바꾸세요 (한글/영문 모두 가능)
classes = ["chat", "receipt", "code", "shopping", "travel",
           "food", "document", "youtube", "unknown"]

for c in classes:
    os.makedirs(os.path.join(base, c), exist_ok=True)

print("생성 완료:", os.listdir(base))

# %% [1] 라이브러리 & GPU 확인 -------------------------------
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

print("TensorFlow:", tf.__version__)
print("GPU:", tf.config.list_physical_devices("GPU"))
# GPU가 안 잡히면 Colab 메뉴: 런타임 > 런타임 유형 변경 > 하드웨어 가속기 > GPU

# %% [2] (선택) 구글 드라이브 마운트 -------------------------
# 데이터가 드라이브에 있다면 주석 해제
# from google.colab import drive
# drive.mount("/content/drive")

# %% [3] 기본 설정 -------------------------------------------
# 데이터 폴더 구조 (라벨 = 하위 폴더 이름):
#   data/
#     ├── 고양이/  img1.jpg ...
#     ├── 강아지/  img2.jpg ...
#     └── 새/      img3.jpg ...
DATA_DIR   = "/content/data"      # 데이터 경로로 수정하세요
IMG_SIZE   = (224, 224)           # EfficientNetB0 기본 입력 크기
BATCH_SIZE = 4  # 실제: 32 / 테스트: 4
SEED       = 123
AUTOTUNE   = tf.data.AUTOTUNE

# %% [4] 데이터 로드 & 70:15:15 분할 -------------------------
# 먼저 70%(train) / 30%(임시) 로 나눈 뒤, 임시를 다시 절반씩 val/test로 분할
train_ds = tf.keras.utils.image_dataset_from_directory(
    DATA_DIR,
    validation_split=0.3,
    subset="training",
    seed=SEED,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    label_mode="int",
)

val_test_ds = tf.keras.utils.image_dataset_from_directory(
    DATA_DIR,
    validation_split=0.3,
    subset="validation",
    seed=SEED,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    label_mode="int",
)

class_names = train_ds.class_names
num_classes = len(class_names)
print("클래스:", class_names, "| 개수:", num_classes)

# 임시셋(30%)을 val 15% / test 15% 로 분할
n_batches = tf.data.experimental.cardinality(val_test_ds).numpy()
val_ds  = val_test_ds.take(n_batches // 2)
test_ds = val_test_ds.skip(n_batches // 2)

# 성능 최적화: 캐시 + 프리페치
train_ds = train_ds.cache().shuffle(1000).prefetch(AUTOTUNE)
val_ds   = val_ds.cache().prefetch(AUTOTUNE)
test_ds  = test_ds.cache().prefetch(AUTOTUNE)

# %% [5] 데이터 증강 -----------------------------------------
# 데이터가 적을수록 효과가 큽니다. (입력은 0~255 범위 그대로 사용)
data_augmentation = tf.keras.Sequential([
    tf.keras.layers.RandomFlip("horizontal"),
    tf.keras.layers.RandomRotation(0.1),
    tf.keras.layers.RandomZoom(0.1),
    tf.keras.layers.RandomContrast(0.1),
], name="data_augmentation")

# %% [6] 모델 구성 (베이스는 동결) ---------------------------
# 주의: EfficientNet은 내부에 정규화가 포함돼 있어
#       입력을 0~255 그대로 넣습니다. (별도 Rescaling 불필요)
base_model = tf.keras.applications.EfficientNetB0(
    include_top=False,
    weights="imagenet",
    input_shape=IMG_SIZE + (3,),
)
base_model.trainable = False   # 1단계: 특징 추출만 학습

inputs = tf.keras.Input(shape=IMG_SIZE + (3,))
x = data_augmentation(inputs)
x = base_model(x, training=False)
x = tf.keras.layers.GlobalAveragePooling2D()(x)
x = tf.keras.layers.Dropout(0.3)(x)
outputs = tf.keras.layers.Dense(num_classes, activation="softmax")(x)

model = tf.keras.Model(inputs, outputs)
model.compile(
    optimizer=tf.keras.optimizers.Adam(1e-3),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"],
)
model.summary()

# %% [7] 1단계 학습: 특징 추출 ------------------------------
callbacks = [
    tf.keras.callbacks.EarlyStopping(
        monitor="val_loss", patience=5, restore_best_weights=True),
    tf.keras.callbacks.ModelCheckpoint(
        "best_model.keras", monitor="val_accuracy", save_best_only=True),
]

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=3,               # 실제: 20 / 테스트: 3
    callbacks=callbacks,
)

# %% [8] 2단계 학습: 미세조정(Fine-tuning) -------------------
# 베이스 상위 일부 층만 풀고 아주 낮은 학습률로 추가 학습.
# (데이터가 클래스당 1,000장 이상일 때 효과가 큽니다)
base_model.trainable = True
FINE_TUNE_AT = len(base_model.layers) - 30   # 마지막 30개 층만 학습
for layer in base_model.layers[:FINE_TUNE_AT]:
    layer.trainable = False

model.compile(
    optimizer=tf.keras.optimizers.Adam(1e-5),   # 반드시 낮은 LR
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"],
)

history_ft = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=10,
    callbacks=callbacks,
)

# %% [9] 테스트셋 최종 평가 ----------------------------------
test_loss, test_acc = model.evaluate(test_ds)
print(f"\n테스트 정확도: {test_acc:.4f} | 손실: {test_loss:.4f}")

# %% [10] 학습 곡선 시각화 -----------------------------------
def plot_history(*histories):
    acc, val_acc, loss, val_loss = [], [], [], []
    for h in histories:
        acc      += h.history["accuracy"]
        val_acc  += h.history["val_accuracy"]
        loss     += h.history["loss"]
        val_loss += h.history["val_loss"]
    epochs = range(1, len(acc) + 1)
    plt.figure(figsize=(12, 4))
    plt.subplot(1, 2, 1)
    plt.plot(epochs, acc, label="train"); plt.plot(epochs, val_acc, label="val")
    plt.title("Accuracy"); plt.legend()
    plt.subplot(1, 2, 2)
    plt.plot(epochs, loss, label="train"); plt.plot(epochs, val_loss, label="val")
    plt.title("Loss"); plt.legend()
    plt.show()

plot_history(history) # 테스트
# plot_history(history, history_ft) # 실제

# %% [11] 모델 저장 & 단일 이미지 예측 ----------------------
model.save("image_classifier.keras")

def predict_image(path):
    img = tf.keras.utils.load_img(path, target_size=IMG_SIZE)
    arr = tf.keras.utils.img_to_array(img)[None, ...]   # 배치 차원 추가
    probs = model.predict(arr)[0]
    idx = int(np.argmax(probs))
    print(f"예측: {class_names[idx]} ({probs[idx]*100:.1f}%)")

# predict_image("/content/test.jpg")

# %% [12] 안드로이드 배포용 TFLite 변환 ----------------------
import tensorflow as tf

model = tf.keras.models.load_model("image_classifier.keras")

converter = tf.lite.TFLiteConverter.from_keras_model(model)
# 안드로이드 권장: 동적 범위 양자화 (용량 약 1/4, 속도↑, 정확도 손실 거의 없음)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()

with open("image_classifier.tflite", "wb") as f:
    f.write(tflite_model)

# 라벨 순서 저장 (앱에서 출력 인덱스 → 클래스 이름 매핑에 필수)
with open("labels.txt", "w", encoding="utf-8") as f:
    f.write("\n".join(class_names))

print("변환 완료:", class_names)

# 파일 내려받기 (Android Studio로 옮기려면)
from google.colab import files
files.download("image_classifier.tflite")
files.download("labels.txt")